name: Meu primeiro workflow no GuitHub Actions

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_job:
    name: Executando o job de teste
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
  
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: rm360138
          password: ${{ SECRETS.SECRETE }}          
